import { type TrainingEvent } from '../types/trainingEvent';

const trainings = [
  {
    id: '1',
    name: 'BLS - BASIC LIFE SUPPORT',
    description: '',
    companyName: 'CCD Skills',
    category: 'Medycyna',
    startDate: new Date('2025-01-25'),
    location: 'Myślenice',
    latitude: 49.83333,
    longitude: 19.93333,
    price: 350,
    duration: '8 h',
    companyLogoUrl: 'http://ccdskills.pl/wp-content/uploads/2023/10/CCD-Skills-logo-blk__rgb.png',
  },
  {
    id: '2',
    name: 'SD01 - PREWENCJA',
    description: '',
    companyName: 'CCD Skills',
    category: 'Samoobrona',
    startDate: new Date('2025-01-26'),
    location: 'Myślenice',
    latitude: 49.83333,
    longitude: 19.93333,
    price: 250,
    duration: '8 h',
    companyLogoUrl: 'http://ccdskills.pl/wp-content/uploads/2023/10/CCD-Skills-logo-blk__rgb.png',
  },
  {
    id: '3',
    name: 'D01 - Drony',
    description: '',
    companyName: 'Predadron',
    category: 'Drony',
    startDate: new Date('2025-02-08'),
    location: 'Słomniki k. Krakowa',
    latitude: 50.08333,
    longitude: 20.13333,
    price: 800,
    duration: '16 h',
    companyLogoUrl: 'http://ccdskills.pl/wp-content/uploads/2023/10/CCD-Skills-logo-blk__rgb.png',
  },
  {
    id: '4',
    name: 'C01 - Świadmość cyfrowa',
    description: '',
    companyName: 'PartnerMed',
    category: 'Cyberbezpieczeństwo',
    startDate: new Date('2025-03-01'),
    location: 'Myślenice/PartnerMed',
    latitude: 49.83333,
    longitude: 19.93333,
    price: 1600,
    duration: '16 h',
    companyLogoUrl: 'http://ccdskills.pl/wp-content/uploads/2023/10/CCD-Skills-logo-blk__rgb.png',
  },
  {
    id: '5',
    name: 'C02A - Osint',
    description: '',
    companyName: 'PartnerMed',
    category: 'Cyberbezpieczeństwo',
    startDate: new Date('2025-03-02'),
    location: 'Myślenice/PartnerMed',
    latitude: 49.83333,
    longitude: 19.93333,
    price: 2600,
    duration: '16 h',
    companyLogoUrl: 'http://ccdskills.pl/wp-content/uploads/2023/10/CCD-Skills-logo-blk__rgb.png',
  },
  {
    id: '6',
    name: 'S01 - Strzelectwo',
    description: '',
    companyName: 'CCD Skills',
    category: 'Strzelectwo',
    startDate: new Date('2025-03-03'),
    location: 'Myślenice',
    latitude: 49.83333,
    longitude: 19.93333,
    price: 450,
    duration: '8 h',
    companyLogoUrl: 'http://ccdskills.pl/wp-content/uploads/2023/10/CCD-Skills-logo-blk__rgb.png',
  },
  {
    id: '7',
    name: 'P01 - Przetrwanie',
    description: '',
    companyName: 'CCD Skills',
    category: 'Przetrwanie',
    startDate: new Date('2025-03-04'),
    location: 'Myślenice',
    latitude: 49.83333,
    longitude: 19.93333,
    price: 350,
    duration: '8 h',
    companyLogoUrl: 'http://ccdskills.pl/wp-content/uploads/2023/10/CCD-Skills-logo-blk__rgb.png',
  },
  {
    id: '8',
    name: 'BLS - BASIC LIFE SUPPORT',
    description: '',
    companyName: 'CCD Skills',
    category: 'Medycyna',
    startDate: new Date('2025-01-25'),
    location: 'Kraków',
    latitude: 50.08333,
    longitude: 19.93333,
    price: 350,
    duration: '8 h',
    companyLogoUrl: 'http://ccdskills.pl/wp-content/uploads/2023/10/CCD-Skills-logo-blk__rgb.png',
  },
  {
    id: '9',
    name: 'SD01 - PREWENCJA',
    description: '',
    companyName: 'CCD Skills',
    category: 'Samoobrona',
    startDate: new Date('2025-01-26'),
    location: 'Kraków',
    latitude: 50.08333,
    longitude: 19.93333,
    price: 250,
    duration: '8 h',
    companyLogoUrl: 'http://ccdskills.pl/wp-content/uploads/2023/10/CCD-Skills-logo-blk__rgb.png',
  },
  {
    id: '10',
    name: 'D01 - Drony',
    description: '',
    companyName: 'Predadron',
    category: 'Drony',
    startDate: new Date('2025-02-08'),
    location: 'Kraków',
    latitude: 50.08333,
    longitude: 19.93333,
    price: 800,
    duration: '16 h',
    companyLogoUrl: 'http://ccdskills.pl/wp-content/uploads/2023/10/CCD-Skills-logo-blk__rgb.png',
  },
] satisfies TrainingEvent[];

export async function searchTrainingEvents(name: string): Promise<TrainingEvent[]> {
  return trainings.filter((training) => training.name.toLowerCase().includes(name.toLowerCase()));
}
