services:
  localstack:
    image: localstack/localstack
    container_name: justjoinus-localstack
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT: http://127.0.0.1:4566
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      DATA_DIR: /tmp/localstack/data
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  database-postgres:
    image: postgis/postgis:16-3.4
    container_name: justjoinus-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: justjoinusdb
    ports:
      - 5432:5432
    volumes:
      - justjoinus-pgdata:/var/lib/postgresql/data

volumes:
  justjoinus-pgdata:
